obj-$(CONFIG_HAVE_IMX_GPC) += gpc.o
obj-$(CONFIG_IMX7_PM_DOMAINS) += gpcv2.o
obj-$(CONFIG_HAVE_IMX_MU) += mu/
obj-$(CONFIG_SOC_IMX8MQ) += busfreq-imx8mq.o gpc-psci.o src.o sc/
obj-$(CONFIG_HAVE_IMX8_SOC) += soc-imx8.o
